### ISSUE TITLE
Mistake in the lmeter documentation

### ISSUE THREAD

**Issue by Wielebny666** [littlevgl/docs#102]
Hi,
https://github.com/littlevgl/docs/blob/master/en/object-types/lmeter.md#range-and-angles
> ...default line number is 31.

in code 
```
ext->line_cnt    = 21;  /*Odd scale number looks better*/
```

**Comment by kisvegabor** [comment]
Hi,

Thank, I've fixed it here: https://github.com/littlevgl/docs/commit/df5829d56657748a2fb1638a5d64ee162cee7bc4

I'll rebuild the docs later today.
