### ISSUE TITLE
Some examples not showing in online documentation

### ISSUE THREAD

**Issue by tonystuart** [littlevgl/docs#106]
**Describe the bug**

The example section in the online documentation (containing the example image and code fragments) is not currently being displayed for some widget types.

**To Reproduce**

These don't work:

https://docs.littlevgl.com/en/html/object-types/ddlist.html
https://docs.littlevgl.com/en/html/object-types/list.html
https://docs.littlevgl.com/en/html/object-types/page.html

These do:

https://docs.littlevgl.com/en/html/object-types/win.html
https://docs.littlevgl.com/en/html/object-types/table.html

**Expected behavior**

The example sections were working until very recently.

**Screenshots**

![Lvgl-Missing-Example 2020-05-16a](https://user-images.githubusercontent.com/1226472/82123133-9b7a1780-974c-11ea-8d8c-f4ad1b3794c8.jpg)

**Additional context**

I tried this in Chrome 81 and Firefox 76 and also tried emptying the browser cache and doing a hard refresh.

**Comment by embeddedt** [comment]
It's strange because they all link to the examples in the same way.

https://github.com/littlevgl/docs/blob/master/en/object-types/ddlist.md#example
https://github.com/littlevgl/docs/blob/master/en/object-types/win.md#example

I wonder whether some of the files (e.g. the `lv_win` one) weren't rebuilt.

**Comment by tonystuart** [comment]
I just realized that too, and it looks like those files haven't been changed in a while.

**Comment by embeddedt** [comment]
It does not appear to be affecting the v7 docs (the [dropdown example](https://docs.littlevgl.com/v7/en/html/widgets/dropdown.html#example) works fine), so I suspect that something was broken in the process of remaking the examples for v7. 

We can probably fix it at the same time that we move the v7 docs to the main page and 6.1 to it's own subdirectory.

**Comment by tonystuart** [comment]
That's great... thanks for the pointer to the v7 docs... I'll use them.

**Comment by kisvegabor** [comment]
I've fixed it, thank you for pointing it out.
