### ISSUE TITLE
Is the page up to date?

### ISSUE THREAD

**Issue by C47D** [littlevgl/docs#16]
Hi,

I'm not very familiar with the docs page (https://docs.littlevgl.com/), is it up to date? Some of the pages i been translating still on English.

Regards

**Comment by kisvegabor** [comment]
The documentation needs to be rebuilt manually. See: https://github.com/littlevgl/docs#how-to-use-this-documentation

I did it few minutes ago, now the pages are translated.

**Comment by C47D** [comment]
Thanks!
