### ISSUE TITLE
Translating for v6.0

### ISSUE THREAD

**Issue by kisvegabor** [littlevgl/docs#21]
Hi,

v6.0 and the new docs have been released. Translating the docs has now started.

If you are interested in the translation please volunteer here to discuss the details. 
 
When you read the English documentation you will surely find typos, grammatical errors, or maybe sentences which don't make sense at all. In this case please send PRs.

If a part was difficult to understand please also notify about it.

**Comment by xiongyumail** [comment]
Count me in, I can translate to Chinese.

**Comment by kisvegabor** [comment]
@xiongyumail
 
Thank you in advance!

@C47D @devfabiosilva @seyyah 

You were also interested in the translations earlier. Do you have time and interest to translate the documentation of v6.0?

**Comment by seyyah** [comment]
We'll try to translate in Turkish.

**Comment by kisvegabor** [comment]
I've just released v6.0 and published the new documentation: https://docs.littlevgl.com/

Give me a few days to stabilize things and get some initial feedback. Next week I'll prepare the docs for the translations.

**Comment by kisvegabor** [comment]
I've prepared the docs to add the translations. 
Now there is a `zh` and a `tr` folder with the original English content.

In the readme, there is a description about how to set up Sphynx to build the docs. However, it's not required. If you "just" translate the `md` files and send PRs, I'll rebuild it.

It's not required to build all the pages at once. You can send PRs for smaller chunks too.

Feel free to send PRs for the English versions too. I'm sure there some typos and non-sense sentences in it. :sweat_smile: 

Let me know if you have any questions!

--- 

If anybody else is interested in translating the docs, let me know and I'll add the required folder.

**Comment by XQDD** [comment]
I have a little question is that why not use smarter I18n strategy as https://hosted.weblate.org/projects/godot-engine/godot-docs/ does,
if the English doc changed, other languages would not change and they will become old docs.

**Comment by kisvegabor** [comment]
Wow, that looks amazing!
I'll check it today or tomorrow.

**Comment by kisvegabor** [comment]
I've made some experiments:
- I was able to compile the docs to `pot` and `po` files (output of gettext) but all the formatting was lost. The docs should be rewritten in `rst` format instead of `md` make it work correctly. [rst summary](https://learnxinyminutes.com/docs/rst/)
- [Weblate](https://weblate.org/en-gb/) was working in localhost but not on a server
- Tried [Zanata](https://translate.zanata.org/) (similar to Weblate but has free hosting) was working online but cli tool wasn't working

My conclusion is Zanata could work but the main issue is the lost formatting of the Markdown files. Reformatting the whole docs could be an option only if some people volunteer to help with that.

**Comment by XQDD** [comment]
Why format will be lost?  we can regard it as a plain txt file, and the reason we use these tools just find a way to track the changes in the new file. Can we just rename all file with add .txt suffix then upload to zanata for translation, after that, we just download it and rename it back and  build it.
![image](https://user-images.githubusercontent.com/20871761/61112804-4f709d80-a4bf-11e9-9d83-cdf6d03cf024.png)

**Comment by xiongyumail** [comment]
@kisvegabor 
Can this tool translate automatically? I can make adjustments based on machine translation.

**Comment by kisvegabor** [comment]
@xiongyumail 
AFAIK it only gives suggestions based on other translations in other projects (called Translation memory) 

You can try it here: https://translate.zanata.org/iteration/view/littlevgl-docs/v6.0-doc1?dswid=-7433

@XQDD 
I've tried it and it could work. `zanata-cli` is not working for me but it would be very important to make things automated.

**Comment by XQDD** [comment]
what java version are you use?

**Comment by XQDD** [comment]
Are you familiar with Java? try java8 or add 
[2.3.0.zip](https://github.com/littlevgl/docs/files/3385903/2.3.0.zip) this jar package to your java class path

**Comment by kisvegabor** [comment]
It's working after switching to java8 from java11 with `sudo update-alternatives --config java`.

Now I test Zantana with the cli tool

**Comment by XQDD** [comment]
And I think Weblate not mere run localhost, it could run on a server, for example:
https://translate.yunohost.org/
But which is better I have no idea

**Comment by kisvegabor** [comment]
Weblate seems better to me but Zantana has free hosting and also should do the job.

I've written a small script to create `*.md.txt` files and push the docs to Zantana.
Here are the files: https://translate.zanata.org/iteration/view/littlevgl-docs/v6.0-doc1/languages?dswid=-6624

The "pull" script is in progress.

**Comment by XQDD** [comment]
But we can't edit it, It seems that you should grant permission to us, and if you confirm to use it, you can update REAMDE.md point out that how to contribute for translation

**Comment by kisvegabor** [comment]
> But we can't edit it, It seems that you should grant permission to us,

I see. I added you to the group and granted permission to translate the Chinese documentation.
How it's working?
If all fine I'll add it to the README.

**Comment by XQDD** [comment]
It seems good, but Idk how to mark some line as "not need translate"
![image](https://user-images.githubusercontent.com/20871761/61130344-0b928e00-a4e9-11e9-9215-5786fc620c21.png)

**Comment by kisvegabor** [comment]
I've noticed this "issue" but didn't find a way to mark paragraphs.

**Comment by XQDD** [comment]
Well, It doesn't matter, copy it is enough, if English doc changes, just copy again
![image](https://user-images.githubusercontent.com/20871761/61131984-06374280-a4ed-11e9-8c40-0ca142f8a93f.png)

**Comment by kisvegabor** [comment]
> I've noticed this "issue" but didn't find a way to mark paragraphs.

If you leave a translation empty it will use the original text.
See: https://docs.littlevgl.com/zh-CN/html/index.html

I've just found this but doesn't work yet.
 http://docs.zanata.org/en/release/user-guide/documents/raw-documents/#inline-tags

**Comment by embeddedt** [comment]
@kisvegabor If at some point we do need to convert from Markdown to reStructuredText then maybe [pandoc](https://pandoc.org/index.html) would be useful.

I used it once in another project to convert HTML documentation to Markdown and it worked very well.

**Comment by kisvegabor** [comment]
@embeddedt 
Good to know thank you!

**Comment by XQDD** [comment]
@xiongyumail 有空一起翻译https://github.com/littlevgl/docs#translate-the-documentation

**Comment by embeddedt** [comment]
@XQDD Please comment in English so that everyone can understand it. :smiley:

**Comment by xiongyumail** [comment]
@XQDD 好的呀，我们怎么开始呢？

@embeddedt We are talking about how to translate to Chinese.

**Comment by XQDD** [comment]
@xiongyumail 他有说,先在这里注册一个账号https://translate.zanata.org/account/register?dswid=8085，然后去https://forum.littlevgl.com/t/translate-the-documentation/238?u=kisvegabor留言账号名称和国家，他会分配权限

**Comment by kisvegabor** [comment]
As the translation has stated on Zanata I close this issue.

Thank you for your contribution.
