### ISSUE TITLE
Code snippets need a license

### ISSUE THREAD

**Issue by embeddedt** [littlevgl/docs#28]
I'm not a lawyer, but I think there are legal ramifications to using code snippets that are not licensed from documentation.

Is it possible to add a statement below the copyright saying that "Code snippets are licensed under the MIT license"?

**Comment by kisvegabor** [comment]
As the snippets now come from `lv_examples` we can add the license there. What do you think?

**Comment by embeddedt** [comment]
@kisvegabor Sounds good!

**Comment by kisvegabor** [comment]
I've just added the license file to the `rework` branch.
https://github.com/littlevgl/lv_examples/blob/rework/LICENCE.txt

**Comment by embeddedt** [comment]
@kisvegabor Great!

I renamed to `LICENSE.md` so that GitHub will detect it as being MIT-licensed. It shouldn't affect anything else.

**Comment by kisvegabor** [comment]
Great, thanks!
