### ISSUE TITLE
SSL certificate issue

### ISSUE THREAD

**Issue by embeddedt** [littlevgl/docs#4]
Browsing to https://doc.littlevgl.com or http://docs.littlevgl.com now gives an invalid certificate error in my browser.

**Comment by embeddedt** [comment]
Hmm. It seems to have resolved itself after a few minutes. Maybe it was just my browser's cache.

**Comment by kisvegabor** [comment]
I've just moved `doc.littlevgl.com` to `docs.littelvgl.com`. I've just realized everybody uses `docs` :smile: 

GitHub needs 24 hours to generate the SSL certificate for the new domain. So it will be fixed tomorrow.

 http://docs.littlevgl.com should work now but all the link point to the `https` version.

**Comment by kisvegabor** [comment]
I was faster. I've just enabled HTTPS. Now all the links should work.
