### ISSUE TITLE
Quick overview lvgl site missing variable declaration

### ISSUE THREAD

**Issue by baldhead69** [littlevgl/docs#52]
Hi,

I dont know if here are the right place to inform this, but.....

Link: https://docs.littlevgl.com/en/html/get-started/quick-overview.html
Quick overview:
Implement and register a function which can read an input device. E.g. for a touch pad:
I think are missing this variable(struct) declaration in first line.
lv_indev_drv_t indev_drv;

Thank's.

**Comment by baldhead69** [comment]
Original:
lv_indev_drv_init(&indev_drv);                          /*Descriptor of a input device driver*/
indev_drv.type = LV_INDEV_TYPE_POINTER;    /*Touch pad is a pointer-like device*/
indev_drv.read_cb = my_touchpad_read;         /*Set your driver function*/
lv_indev_drv_register(&indev_drv);                   /*Finally register the driver*/


Correct(maybe):
lv_indev_drv_t indev_drv;                                               /*Descriptor of a input device driver*/
lv_indev_drv_init(&indev_drv);                                       /*Basic initialization*/
**_lv__**indev_drv.type = LV_INDEV_TYPE_POINTER;    /*Touch pad is a pointer-like device*/
**_lv__**indev_drv.read_cb = my_touchpad_read;         /*Set your driver function*/
lv_indev_drv_register(&indev_drv);                                /*Finally register the driver*/

Are missing two "lv_"  too.

**Comment by embeddedt** [comment]
> I think are missing this variable(struct) declaration in first line.

Thank you! Fixed.

> Are missing two "lv_" too.

Wrong. The type name is `lv_indev_drv_t` but the variable name is just `indev_drv`. There is no need to add an `lv_` to those two lines.

**Comment by kisvegabor** [comment]
Thank you for the report and fix!
