### ISSUE TITLE
Where is the <sys/mman.h>?

### ISSUE THREAD

**Issue by JoshuaKim6502** [littlevgl/docs#73]
Hi,

I appreciate the LittlevGL. Regarding the PC simulator, I have followed the steps and succeed in running make all.  However,  I got the following error.

make all 
'Building file: ../lv_drivers/display/fbdev.c'
../lv_drivers/display/fbdev.c:17:10: fatal error: sys/mman.h: No such file  or directory
 #include <sys/mman.h>
          ^~~~~~~~~~~~

I can hardly find the "mman.h" in MinGW, SDL, and the simulator source itself.  Would you help me to figure out this error?

Thanks,
Joshua

**Comment by kisvegabor** [comment]
Hi, 

this issue was fixed a few days ago. You can update the PC simulator or just set `LV_USE_FBDEV   0` in `lv_drv_conf.h`.

**Comment by JoshuaKim6502** [comment]
Hi, Thanks for your answer. I am fortunate to get the latest fixed solution.  Once I modified the `lv_drv_conf.h` as follows, I succeed!

`#define USE_FBDEV           0`

![image](https://user-images.githubusercontent.com/54395703/67446165-a0f60000-f64a-11e9-908b-f7a7d6266c61.png)

Thanks again!
Joshua

**Comment by kisvegabor** [comment]
Great, you're welcome! :)
