### ISSUE TITLE
change button label 

### ISSUE THREAD

**Issue by himsha** [littlevgl/docs#81]
i i had created below button how to change its font size?

`    // create button
    lv_obj_t * btnSystemOnOFF = lv_btn_create(window, NULL);
    lv_obj_align(btnSystemOnOFF, NULL, LV_ALIGN_IN_TOP_RIGHT, -24, 40);
    lv_obj_set_size(btnSystemOnOFF, 125, 40);
    lv_btn_set_toggle(btnSystemOnOFF, true);
    lv_btn_toggle(btnSystemOnOFF);
    // button label
    ButtonLabel = lv_label_create(btnSystemOnOFF, NULL);
    lv_label_set_text(ButtonLabel, "System ON");
    // button action
    lv_imgbtn_set_action(btnSystemOnOFF, LV_BTN_ACTION_CLICK, btn_click_SystemOnOFF);`

**Comment by embeddedt** [comment]
You would need to change the font used in the button's style. See https://docs.littlevgl.com/en/html/object-types/btn.html#styles and https://docs.littlevgl.com/en/html/overview/style.html.

----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.

**Comment by himsha** [comment]
i had done below font won't change

`	static lv_style_t style1; /*Declare a new style. Should be `static`*/
	lv_style_copy(&style1, &lv_style_plain); /*Copy a buil-in style*/
	style1.body.main_color = LV_COLOR_RED; /*Main color*/
	style1.body.grad_color = LV_COLOR_RED; /*Gradient color (orange)*/
	style1.body.radius = 3;
	style1.text.color = LV_COLOR_WHITE;//lv_color_hex3(0x0F0); /*Label color (green)*/
	style1.text.font = &lv_font_dejavu_20; /*Change font*/

    lv_obj_t * ButtonLabel;

    // create button
    lv_obj_t * btnSystemOnOFF = lv_btn_create(window, NULL);
    lv_obj_align(btnSystemOnOFF, NULL, LV_ALIGN_IN_TOP_RIGHT, -24, 40);
    lv_obj_set_size(btnSystemOnOFF, 125, 40);
    lv_btn_set_toggle(btnSystemOnOFF, true);
    lv_btn_toggle(btnSystemOnOFF);
    // button label
    ButtonLabel = lv_label_create(btnSystemOnOFF, NULL);
    lv_label_set_text(ButtonLabel, "System ON");
    // button action
    lv_imgbtn_set_action(btnSystemOnOFF, LV_BTN_ACTION_CLICK, btn_click_SystemOnOFF);

    lv_btn_set_style(btnSystemOnOFF, LV_BTN_STYLE_REL, &style1);
    lv_btn_set_style(btnSystemOnOFF, LV_BTN_STYLE_PR, &style1);`

**Comment by himsha** [comment]
done above.

**Comment by embeddedt** [comment]
`lv_font_dejavu_20` is a font with size 20px. 

If you want a smaller font you have to either enable one of the builtin ones in `lv_conf.h` and then use it, or use the font converter to create a font with a smaller size.

Again, please use the forum for asking questions. We use issues for discussing new features/bugs.
