### ISSUE TITLE
Unify conf.py files

### ISSUE THREAD

**Issue by embeddedt** [littlevgl/docs#98]
Currently, we have a `conf.py` file for each language. There doesn't seem to be anything language-specific within each file, so can we symlink them and only have one actual `conf.py` being used?

I came across this while looking for the spot to update the documentation's version number (as it still says `6.0` rather than `6.1`).

**Comment by kisvegabor** [comment]
I've just added symlinks as you suggested, updated the version and updated and rebuilt the docs.

**Comment by embeddedt** [comment]
Perfect. Thanks!
